#-------------------------------
# General Site Settings
title: NONODE
logo: # You can add own logo. For example '/images/logo.png'.
description: NONODE - Personal site of Pavel Necas.
baseurl: "" # The subpath of your site, e.g. /blog
url: "http://nonode.dev" # The base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Author Settings
author:
  name: Pavel Nečas
  avatar: '/images/about/about-1.jpg'


#-------------------------------
# Hero Settings
hero:
  title: Pavel Nečas
  description: > 
    Game Producer and Unreal Generalist, Problem Solver, Immersive Experiences Creator. Welcome! 
    Place where I post my ideas and projects. Some large, some small. 
    My Discord is Pavelios 4451. 
  image: '/images/backgrounds/bg-1.jpg'

#-------------------------------
# Gamedev Section Settings
gamedev:
  title: My Gamedev Journey
  description: > 
    Game Producer and Unreal Generalist, Problem Solver, Immersive Experiences Creator. Welcome! 
    Place where I post my ideas and projects. Some large, some small. 
    My Discord is Pavelios 4451. 



#-------------------------------
# Contact Settings
contact:
  email: f/xpzelroq # Add your email for contact form
  description: Because of spam bots, please send me message through here and I will get back to asap! Or you can use this pavel (at & at) nonode . dev . My Discord is Pavelios 4451.  # Add a description of your form

# NOTE
# Norlin theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Footer section
# Example of adding a new link to the footer - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
# - {icon: "ion-logo-twitter", link: "https://twitter.com"}
# - {icon: "ion-logo-facebook", link: "https://facebook.com"}
# - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# - {icon: "ion-logo-instagram", link: "https://instagram.com"}
# - {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
- {icon: "ion-logo-youtube", link: "https://www.youtube.com/channel/UCbjAhPuKCbcNuSiPArQujiA"}
- {icon: "ion-logo-github", link: "https://github.com/Pavelioso/"}
# - {icon: "ion ion-logo-vimeo", link: "https://vimeo.com/"}


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvodstudio-demo # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: G-610B5SJ5H3 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: enable # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp-identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-tagging

paginate: 15
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed